// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARq76Hg218fMPi4qjbY4LfXewyZeJRMOk',
    appId: '1:521840944252:web:e73596cd01f05c112455f9',
    messagingSenderId: '521840944252',
    projectId: 'comas1163',
    authDomain: 'comas1163.firebaseapp.com',
    storageBucket: 'comas1163.firebasestorage.app',
    measurementId: 'G-MH9J6126QP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo7CL0I_cTOMIuedpvQYfGFOPRn8vHR5Q',
    appId: '1:521840944252:ios:cdec55653c97f47d2455f9',
    messagingSenderId: '521840944252',
    projectId: 'comas1163',
    storageBucket: 'comas1163.firebasestorage.app',
    iosBundleId: 'com.example.camisetaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARq76Hg218fMPi4qjbY4LfXewyZeJRMOk',
    appId: '1:521840944252:web:20629bcd80ddf9852455f9',
    messagingSenderId: '521840944252',
    projectId: 'comas1163',
    authDomain: 'comas1163.firebaseapp.com',
    storageBucket: 'comas1163.firebasestorage.app',
    measurementId: 'G-PZV2JDHVXM',
  );
}
